=== ireneheredia/brayascafe/xml/branches.dtd
<!ELEMENT branches (branch+)>
<!ELEMENT branch (name, address, contact, openingHours, googleMaps)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT openingHours (#PCDATA)>
<!ELEMENT googleMaps (#PCDATA)>

=== ireneheredia/brayascafe/xml/branches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">
<branches>
    <branch>
        <name>76 Devonshire St, Surry Hills NSW</name>
        <address>76 Devonshire St, Surry Hills NSW</address>
        <contact>02 9211 1234</contact>
        <openingHours>Mon - Fri: 6:00 to 14:30, Sat-Sun: 7:00 to 15:00</openingHours>
        <googleMaps>https://www.google.com/maps?q=76+Devonshire+St,+Surry+Hills+NSW</googleMaps>
    </branch>
    <branch>
        <name>451 Pitt St, Haymarket Sydney, NSW</name>
        <address>451 Pitt St, Haymarket Sydney, NSW</address>
        <contact>02 9262 5678</contact>
        <openingHours>Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</openingHours>
        <googleMaps>https://www.google.com/maps?q=451+Pitt+St,+Haymarket+Sydney,+NSW</googleMaps>
    </branch>
    <branch>
        <name>31 Alfred Street, Circular Quay, NSW</name>
        <address>31 Alfred Street, Circular Quay, NSW</address>
        <contact>02 8971 9101</contact>
        <openingHours>Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</openingHours>
        <googleMaps>https://www.google.com/maps?q=31+Alfred+Street,+Circular+Quay,+NSW</googleMaps>
    </branch>
</branches>
